### ISSUE TITLE
EACCES: permission denied, open ´/sys/class/gpio/export´

### ISSUE THREAD

**Issue by desq42** [jacobgelman/homebridge-gpio-valve#2]
…see Error. Do I need to chmod the export-folder for user "homebridge" access?

**Comment by ladvoc** [comment]
In order to determine what is causing this issue, please provide the following information about your system configuration:
- Device [e.g. Raspberry Pi 3]
- OS [e.g. Raspbian Stretch 4.14]
- Node Version [e.g. 8.11.2]

**Comment by desq42** [comment]
Device: Raspberry Pi3
OS = Raspbian 9.4 Stretch
Node = 10.4.0

Homebridge is running with systemd as user homebridge.

**Comment by ladvoc** [comment]
I apologize for not responding sooner. This appears to be an issue with the GPIO library this plugin uses, [onoff](https://www.npmjs.com/package/onoff). Please refer to [this issue](https://github.com/fivdi/onoff/issues/3) from the onoff repository. Let me know if this is helpful.

**Comment by desq42** [comment]
No problem. I could not solve the issue with "onoff", therefore I forked your Plugin (locally) and
taught it to call an url to switch relays on a sonoff 4ch pro. (works for me… ;-)
