### ISSUE TITLE
Can’t automate sprinklers

### ISSUE THREAD

**Issue by lfiocco** [jacobgelman/homebridge-gpio-valve#3]
For some reason I can’t automate the sprinklers using the Apple home app.

I can manually start them with a timer lasting 10-15 minutes works good. 

Under automation I select time of day, I choose a time, but the sprinklers don’t show up as something I can select to switch on? I want to create an automation that will turn on the sprinklers at 4am. So the can run for the time pre-programmed.

**Comment by ladvoc** [comment]
This is either a bug or a limitation of the Home app—even in the latest iOS 12 beta. I cannot imagine why Apple would choose to not allow sprinklers to be automated, so I will submit feedback informing them of this issue.

**Comment by lfiocco** [comment]
I can get it working with home app written by another dev. It does it by creating a trigger and a scene.

But ya Apple needs to bring up the level of their app.

eSystems.ca<http://eSystems.ca>

On Jun 28, 2018, at 12:06 PM, Jacob <notifications@github.com<mailto:notifications@github.com>> wrote:


This is either a bug or a limitation of the Home app—even in the latest iOS 12 beta. I cannot imagine why Apple would choose to not allow sprinklers to be automated, so I will submit feedback informing them of this issue.
